apiVersion: v1
kind: Service

metadata:
  name: {{ include "fittrack.fullname" . }}-backend
  labels:
    {{- include "fittrack.labels" . | nindent 4 }}

spec:
  type: {{ .Values.backend.service.type }}

  selector:
    app: backend

  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
