apiVersion: v1
kind: ConfigMap

metadata:
  name: fittrack-config
  labels:
    {{- include "fittrack.labels" . | nindent 4 }}

data:
  database: {{ .Values.mongodb.auth.database | quote }}
  port: {{ .Values.backend.service.port | quote }}
